//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int logs_id { get; set; }
        public string id_panel { get; set; }
        public int user_id { get; set; }
        public string initial_stage { get; set; }
        public string final_stage { get; set; }
        public System.DateTime date { get; set; }
        public bool result { get; set; }
    
        public virtual user user { get; set; }
    }
}
