//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class stage_deal
    {
        public string id_deal { get; set; }
        public string name_stage { get; set; }
        public string name_stade_ru { get; set; }
    }
}
